accounts/urls.py
from django.urls import path, include
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup")
]

pill_dispenser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from notes.views import note_list_view,finish_item,delete_item,recover_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path("registration/", include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('profile/', TemplateView.as_view(template_name="home/profile.html"), name="profile"),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('note/', note_list_view,name='note-list'),
    path('note/finish-item/<id>/', finish_item,name='finish-note-item'),
    path('note/recover-item/<id>/', recover_item,name='recover-note-item'),
    path('note/delete-item/<id>/', delete_item,name='delete-note-item')
]

accounts/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models
from django.shortcuts import reverse,redirect
from django.contrib.auth.models import User
# Create your models here.

REPEAT_CHOICES = (
    ('daily', '매일'),
    ('mon', '월'),
    ('tue', '화'),
    ('wed', '수'),
    ('thu', '목'),
    ('fri', '금'),
    ('sat', '토'),
    ('sun', '일'),
)
CONTAINER_CHOICES =(
    (1, '1'),
    (2, '2'),
    (3, '3')
)


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    medicine = models.CharField(max_length=100, null=False)
    dosing_time = models.TimeField(null=False, default='08:00')
    repetition = models.TextField(default='daily')
    container = models.IntegerField(null=True)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.medicine

    def get_finish_item_url(self):
        return reverse("finish-note-item",kwargs={
            'id':self.id
        })
    def get_recover_item_url(self):
        return reverse("recover-note-item",kwargs={
            'id':self.id
        })
    def get_delete_item_url(self):
        return reverse("delete-note-item",kwargs={
            'id':self.id
        })
    def get_repeat_display(self):
        repeat_dict = dict(REPEAT_CHOICES)
        repeats = self.repetition.split(',')
        return ', '.join([repeat_dict[repeat] for repeat in repeats])

notes/forms.py
from django import forms
from .models import Note, REPEAT_CHOICES, CONTAINER_CHOICES


class NoteModelForm(forms.ModelForm):
    dosing_time = forms.TimeField(widget=forms.TimeInput(attrs={"class":'timepicker', "placeholder":"HH:MM"}))
    repetition = forms.MultipleChoiceField(choices=REPEAT_CHOICES, widget=forms.CheckboxSelectMultiple(attrs={'class': 'repeat-checkbox'}))
    container = forms.ChoiceField(choices=CONTAINER_CHOICES)
    
    class Meta:
        model = Note
        fields = ['medicine', 'dosing_time', 'repetition', 'container']

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

notes/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .forms import NoteModelForm
from .models import Note
# Create your views here.

@login_required(login_url="/accounts/login/")
def note_list_view(request):
    error_message = None
    form = NoteModelForm()
    if request.method == "POST":
        form = NoteModelForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            if '매일' in form.cleaned_data['repetition']:
                note.repetition = 'daily'
            else:
                note.repetition = ','.join(form.cleaned_data['repetition'])
            print(form.cleaned_data['container'])
            if Note.objects.filter(user=request.user.id, container=form.cleaned_data['container']).exists():
                error_message = "컨테이너가 이미 채워져있습니다."
            else:
                note.save()
                return redirect('note-list')
    else:
        form = NoteModelForm()
        
    to_do_list = Note.objects.filter(user=request.user.id, finished=False)
    finished_list = Note.objects.filter(user=request.user.id, finished=True)
    
    context = {
        'to_do_list': to_do_list,
        'finished_list': finished_list,
        'form': form,
        'error_message': error_message,
    }
    return render(request, "note_list.html", context)

def finish_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.finished=True
    note.save()
    return redirect('note-list')

def recover_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.finished=False
    note.save()
    return redirect('note-list')

def delete_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.delete()
    return redirect('note-list')

notes/templates/notes/note_list.html
{% extends "layouts/base.html" %}

{% block content%}
<div class="collarpse-wrapper">
    <div class="text-center">
        <h1 class="mt-3">투약 리스트
            <a type="button"  data-toggle="collapse" data-target="#collapseExample">
                <i class="fas fa-plus fa-sm text-warning" ></i>
            </a>
        </h1>
        <hr>
    </div>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            {% if error_message %}
                <div class="alert alert-danger">{{ error_message }}</div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group m-3">
                    <label class=" " for="id_container">컨테이너 번호</label>
                    {{form.container}}
                </div>
                <div class="form-group m-3">
                    <label class=" " for="id_medicine">약 이름</label>
                    {{form.medicine}}
                </div>
                <div class="form-group m-3">
                    <label class=" " for="id_dosing_time">투약 시간</label>
                    {{form.dosing_time}}
                </div>
                <div class="form-group m-3">
                    <label class=" " for="id_repeat">반복</label>
                    {{form.repetition}}
                </div>
                <button type="submit" class="btn btn-primary ms-3 mb-2">저장</button>
            </form>
            <!-- {% comment %} endform {% endcomment %} -->
        </div>
    </div>
</div>
<div class="row">
    <div class="container">
        <div class="border rounded-3 col p-2 text-center centered-form center-block position-relative ">
            <h3>예정된 투약</h3>
            {% for note in to_do_list %}
            <div class="card container col-md-10 col-md-offset-1" style="width: 18rem;">
                {% include "note_snippet.html" with note_snippet_var=note type="DELETE" %}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="border rounded-3 col p-2 text-center centered-form center-block position-relative ">
            <h3>종료된 투약</h3>
            {% for note in finished_list %}
            <div class="card container col-md-10 col-md-offset-1" style="width: 18rem;">
                {% include "note_snippet.html" with note_snippet_var=note type="ADD" %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      const dailyCheckbox = document.querySelector('input[value="daily"]');
      const otherCheckboxes = document.querySelectorAll('input.repeat-checkbox:not([value="daily"])');
  
      dailyCheckbox.addEventListener('change', function() {
        if (dailyCheckbox.checked) {
          otherCheckboxes.forEach(function(checkbox) {
            checkbox.checked = false;
          });
        }
      });
  
      otherCheckboxes.forEach(function(checkbox) {
        checkbox.addEventListener('change', function() {
          if (checkbox.checked) {
            dailyCheckbox.checked = false;
          }
        });
      });
    });
  </script>

{% endblock content %}

notes/templates/notes/note_snippet.html
<div class="card-body">
    <h6 class="card-subtitle mb-2">
        <span class="badge bg-{{note.get_label_display }}" style="color:black">
            컨테이너 {{note_snippet_var.container}}
        </span>
    </h6>
    <h5 class="card-title text-capitalize">{{note_snippet_var.medicine}}</h5>
    <p class="card-text">{{note_snippet_var.get_repeat_display}}, {{note_snippet_var.dosing_time}}</p>
        {% if type == "DELETE" %}
            <a href="{{note_snippet_var.get_finish_item_url}}" class="card-link text-success"><i class="fas fa-check"></i></a>
        {% else %}
            <a href="{{note_snippet_var.get_recover_item_url}}" class="card-link text-warning"><i class="fas fa-times"></i></a>
        {% endif %}
        
    <a href="{{note_snippet_var.get_delete_item_url}}" class="card-link text-danger"><i class="fas fa-dumpster"></i></a>
</div>

templates/home.html
<!-- templates/home.html -->
{% extends "layouts/base-fullscreen.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="wrapper" style="text-align: center; padding-top: 20px;">
    {% if user.is_authenticated %}
        <p><a href="{% url 'password_change' %}" class="btn btn-primary">비밀번호 변경</a></p>
        <p><a href="{% url 'logout' %}" class="btn btn-primary">로그아웃</a></p>
    {% else %}
        <p><a href="{% url 'login' %}" class="btn btn-primary">로그인</a></p>
        <p><a href="{% url 'password_reset' %}" class="btn btn-primary">비밀번호 초기화</a></p>
        <p><a href="{% url 'signup' %}" class="btn btn-primary">회원가입</a></p>
    {% endif %}
</div>
{% endblock %}

templates/home/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary border-0 mb-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
              <div class="btn-wrapper text-center">
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/github.svg"></span>
                  <span class="btn-inner--text">Github</span>
                </a>
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/google.svg"></span>
                  <span class="btn-inner--text">Google</span>
                </a>
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">
                <small>Or sign in with credentials</small>
              </div>
              <form role="form" action="/">
                <div class="form-group mb-3">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                    </div>
                    <input class="form-control" placeholder="Email" type="email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="Password" type="password">
                  </div>
                </div>
                <div class="custom-control custom-control-alternative custom-checkbox">
                  <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                  <label class="custom-control-label" for=" customCheckLogin">
                    <span class="text-muted">Remember me</span>
                  </label>
                </div>
                <div class="text-center">
                  <button type="button" class="btn btn-primary my-4">Sign in</button>
                </div>
              </form>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/register.html" class="text-light"><small>Create Account</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="https://appseed.us?ref=j2-argon-demo" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/map.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Google maps</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Maps</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Google maps</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
      <div class="row">
        <div class="col">
          <div class="card border-0">
            <div id="map-default" class="map-canvas" data-lat="40.748817" data-lng="-73.985428" style="height: 600px;"></div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}
      
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

{% endblock javascripts %}

templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Please authenticate <a href="/login.html">Login</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>          
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/page-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 500      
              </div>

              <div class="text-center mb-4">
                Server error, please contact support - <a href="/">Home</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/profile.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<div class="header pb-6 d-flex align-items-center" 
     style="min-height: 500px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white"> 
          Hello {{ current_user.username }}
        </h1>
        <p class="text-white mt-0 mb-5">This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks</p>
        <a href="#!" class="btn btn-neutral">Edit profile</a>
      </div>
    </div>
  </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <a href="#">
                <img src="/static/assets/img/theme/team-4.jpg" class="rounded-circle">
              </a>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <div class="d-flex justify-content-between">
            <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
            <a href="#" class="btn btn-sm btn-default float-right">Message</a>
          </div>
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  <span class="heading">22</span>
                  <span class="description">Friends</span>
                </div>
                <div>
                  <span class="heading">10</span>
                  <span class="description">Photos</span>
                </div>
                <div>
                  <span class="heading">89</span>
                  <span class="description">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <h5 class="h3">
              {{ current_user.username }}
            </h5>
            <div class="h5 font-weight-300">
              {{ current_user.email }}
            </div>
            <div class="h5 mt-4">
              <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
            </div>
            <div>
              <i class="ni education_hat mr-2"></i>University of Computer Science
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Edit profile </h3>
            </div>
            <div class="col-4 text-right">
              <a href="#!" class="btn btn-sm btn-primary">Settings</a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <form>
            <h6 class="heading-small text-muted mb-4">User information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-username">Username</label>
                    <input type="text" id="input-username" class="form-control" placeholder="Username" value="{{ current_user.username }}">
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-email">Email address</label>
                    <input type="email" id="input-email" class="form-control" placeholder="{{ current_user.email }}">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-first-name">First name</label>
                    <input type="text" id="input-first-name" class="form-control" placeholder="First name" value="Lucky">
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-last-name">Last name</label>
                    <input type="text" id="input-last-name" class="form-control" placeholder="Last name" value="Jesse">
                  </div>
                </div>
              </div>
            </div>
            <hr class="my-4" />
            <!-- Address -->
            <h6 class="heading-small text-muted mb-4">Contact information</h6>
            <div class="pl-lg-4">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-address">Address</label>
                    <input id="input-address" class="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" type="text">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-city">City</label>
                    <input type="text" id="input-city" class="form-control" placeholder="City" value="New York">
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-country">Country</label>
                    <input type="text" id="input-country" class="form-control" placeholder="Country" value="United States">
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label class="form-control-label" for="input-country">Postal code</label>
                    <input type="number" id="input-postal-code" class="form-control" placeholder="Postal code">
                  </div>
                </div>
              </div>
            </div>
            <hr class="my-4" />
            <!-- Description -->
            <h6 class="heading-small text-muted mb-4">About me</h6>
            <div class="pl-lg-4">
              <div class="form-group">
                <label class="form-control-label">About Me</label>
                <textarea rows="4" class="form-control" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <!-- Page content -->
  <div class="container mt--8 pb-5">
    <!-- Table -->
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card bg-secondary border-0">
          <div class="card-body px-lg-5 py-lg-5">
            <form role="form">
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                  </div>
                  <input class="form-control" name="username" placeholder="Name" type="text">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                  </div>
                  <input class="form-control" name="password1" placeholder="Password" type="password">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                  </div>
                  <input class="form-control" name="password2" placeholder="Input Password Again" type="password">
                </div>
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary mt-4" value="SignUp">Create account</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a target="_blank" class="font-weight-bold ml-1" target="_blank">Reproduced by Matthew Jung</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a target="_blank" 
                         href="https://www.creative-tim.com">Creative-Tim</a> 
               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a 
                 class="font-weight-bold ml-1" target="_blank">Reproduced by MatthewJung </a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://www.creative-tim.com" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>